flask_project/posts/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed, FileField
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    image_file = FileField('Add an image to your post',
                       validators=[FileAllowed(['jpg', 'png'])])
    submit = SubmitField('Save')

flask_project/posts/routes.py
import datetime

from flask import Blueprint, request, render_template, flash, abort, redirect, \
    url_for
from flask_login import login_required, current_user

from flask_project import db
from flask_project.models import Post
from flask_project.posts.forms import PostForm
from flask_project.users.utils import save_image

posts = Blueprint('posts', __name__)


@posts.route('/')
def allpost():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()). \
        paginate(page=page, per_page=4)
    return render_template('index.html', posts=posts, datetime=datetime)


@posts.route('/posts/user/<int:user_id>')
@login_required
def user_posts(user_id):
    page = request.args.get('page', 1, type=int)
    posts = Post.query.filter(Post.user_id == user_id). \
        order_by(Post.date_posted.desc()).paginate(page=page, per_page=4)
    return render_template('user_posts.html', posts=posts, datetime=datetime)


@posts.route('/post/new', methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        if form.image_file.data:
            image_file = save_image(form.image_file.data)
            post = Post(title=form.title.data, content=form.content.data,
                        user_id=current_user.id, image_file=image_file)
            db.session.add(post)
        else:
            post = Post(title=form.title.data, content=form.content.data,
                        user_id=current_user.id, image_file='default.jpg')
            db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success')
    return render_template('create_post.html', title='New post', form=form,
                           legend='New post')


@posts.route('/post/<int:post_id>')
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post,
                           datetime=datetime)


@posts.route('/post/<int:post_id>/update', methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.user_id != current_user.id:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        if form.image_file.data:
            image_file = save_image(form.image_file.data)
            post.image_file = image_file
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post', post_id=post_id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
        if post.image_file:
            image_file = url_for('static', filename='img/posts_image/'
                                                    + post.image_file)
        else:
            image_file = url_for('static',
                                 filename='img/posts_image/default.png')

        return render_template('create_post.html', title='Update of post.',
                               form=form, legend='Update of post.',
                               image_file=image_file)


@posts.route('/post/<int:post_id>/delete', methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.user_id != current_user.id:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been delete!', 'success')
    return redirect(url_for('posts.allpost'))

flask_project/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from flask_project import db, bcrypt
from flask_project.models import User, Post
from flask_project.users.forms import (RegistrationForm, LoginForm,
                                       UpdateAccountForm, RequestResetForm,
                                       ResetPasswordForm)
from flask_project.users.utils import save_avatar, send_reset_email

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = RegistrationForm()
    if form.validate_on_submit():
        if form.avatar.data:
            avatar = save_avatar(form.avatar.data)
        else:
            avatar = 'default.png'
        hashed_password = bcrypt.generate_password_hash(
            form.password.data).decode('utf-8')
        user = User(username=form.username.data,
                    email=form.email.data,
                    password=hashed_password,
                    image_file=avatar)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! Now you can log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('posts.allpost'))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password,
                                               form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else \
                redirect(url_for('posts.allpost'))
        else:
            flash('Login failed. Please check your email and password.',
                  'attention')
    return render_template('login.html', title='Authentication', form=form)


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.avatar.data:
            avatar_file = save_avatar(form.avatar.data)
            current_user.image_file = avatar_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
        page = request.args.get('page', 1, type=int)
        user = User.query.filter_by(username=form.username.data).first_or_404()
        posts = Post.query.filter_by(author=user) \
            .order_by(Post.date_posted.desc()) \
            .paginate(page=page, per_page=5)
        if user.image_file:
            image_file = url_for('static', filename='profile_avatar/'
                                                    + current_user.image_file)
        else:
            image_file = url_for('static',
                                 filename='profile_avatar/default.png')

        return render_template('account.html', title='Account',
                               image_file=image_file, form=form,
                               posts=posts, user=user)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('posts.allpost'))

@users.route('/reset_password', methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('posts.allpost'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with '
              'instructions on how to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html',
                           title='Reset password',
                           form=form)

@users.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('posts.allpost'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('The link is outdated, try resetting the password again.',
              'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data)\
            .decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been successfully updated.', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html',
                           title='Reset password',
                           form=form)

flask_project/templates/account.html
{% extends "base.html" %}

{% block content %}
    <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ image_file }}">
      </div>

      <form method="POST" action="" enctype="multipart/form-data">
          {{ form.hidden_tag() }}
          <fieldset class="form-group">
              <legend class="border-bottom mb-4">User account</legend>
              <div class="form-group">
                  {{ form.username.label(class="form-control-label") }}
                    {{current_user.username}}

                  {% if form.username.errors %}
                      {{ form.username(class="form-control form-control-lg is-invalid") }}
                      <div class="invalid-feedback">
                          {% for error in form.username.errors %}
                              <span>{{ error }}</span>
                          {% endfor %}
                      </div>
                  {% else %}
                      {{ form.username(class="form-control form-control-lg") }}
                  {% endif %}
              </div>
              <div class="form-group">
                  {{ form.email.label(class="form-control-label") }}
                  {{current_user.email}}
                  {% if form.email.errors %}
                      {{ form.email(class="form-control form-control-lg is-invalid") }}
                      <div class="invalid-feedback">
                          {% for error in form.email.errors %}
                              <span>{{ error }}</span>
                          {% endfor %}
                      </div>
                  {% else %}
                      {{ form.email(class="form-control form-control-lg") }}
                  {% endif %}
              </div>
              <div class="form-group">
                  {{ form.avatar.label() }}
                  {{ form.avatar(class="form-control-file") }}
                  {% if form.avatar.errors %}
                      {% for error in form.avatar.errors %}
                          <span class="text-danger">{{ error }}</span></br>
                      {% endfor %}
                  {% endif %}
              </div>
          </fieldset>
          <div class="form-group">
              {{ form.submit(class="btn btn-outline-info") }}
          </div>
      </form>      
    </div>   

{% endblock content %}

flask_project/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Academy-GB Blog</title>
    <link rel="stylesheet"
          href="{{ url_for('static', filename='fontawesome/css/all.min.css') }}">
    <!-- https://fontawesome.com/ -->
    <link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro&display=swap"
          rel="stylesheet"> <!-- https://fonts.google.com/ -->
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}"
          rel="stylesheet">
    <link href="{{ url_for('static', filename='css/style.css') }}"
          rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@600;900&display=swap" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/errors_css.css') }}" rel="stylesheet">
    <link rel="icon" href="{{ url_for('static', filename='img/ico-icon.png') }}" type="image/png">
</head>
<body>
<header class="tm-header" id="tm-header">
    <div class="tm-header-wrapper">
        <button class="navbar-toggler" type="button"
                aria-label="Toggle navigation">
            <i class="fas fa-bars"></i>
        </button>
        <div class="tm-site-header">
            <div class="mb-3 mx-auto tm-site-logo"><i
                    class="fas fa-times fa-2x"></i></div>
            <h1 class="text-center">Academy-GB Blog</h1>
        </div>
        <nav class="tm-nav" id="tm-nav">
            <ul>
                <li class="tm-nav-item">
                    <a href="/" class="tm-nav-link">
                        <i class="fas fa-home"></i>
                        Blog Home
                    </a>
                </li>
                <li class="tm-nav-item">
                    {% if current_user.is_authenticated %}
                    <a href="{{ url_for('posts.user_posts', user_id=current_user.id) }}"
                                           class="tm-nav-link">
                        <i class="fas fa-pen"></i>
                        My Post
                    </a>
                    {% endif %}
                </li>
                <li class="tm-nav-item">
                    <a href="/about" class="tm-nav-link">
                        <i class="fas fa-users"></i>
                        About Academy-GB Blog
                    </a>
                </li>
                <li class="tm-nav-item">
                    <a href="/contact" class="tm-nav-link">
                        <i class="fas fa-comments"></i>
                        Contact Us
                    </a>
                </li>
            </ul>
        </nav>
        <div class="tm-mb-65">
            <a rel="nofollow" href="https://fb.com/templatemo"
               class="tm-social-link">
                <i class="fab fa-facebook tm-social-icon"></i>
            </a>
            <a href="https://twitter.com" class="tm-social-link">
                <i class="fab fa-twitter tm-social-icon"></i>
            </a>
            <a href="https://instagram.com" class="tm-social-link">
                <i class="fab fa-instagram tm-social-icon"></i>
            </a>
            <a href="https://linkedin.com" class="tm-social-link">
                <i class="fab fa-linkedin tm-social-icon"></i>
            </a>
        </div>
        <p class="tm-mb-80 pr-5 text-white">
            Academy-GB Blog is a multi-purpose HTML template from TemplateMo
            website.
            Left side is a sticky menu bar. Right side content will scroll up
            and down.
        </p>
    </div>
</header>
<div class="container-fluid">
    <!-- Navbar Right Side -->
    <div class="menu_bar">
        {% if current_user.is_authenticated %}
            <a class="menu_link" href="{{ url_for('posts.new_post') }}">
                <i class="fa fa-plus icon-left"></i>Новый пост</a>
            <a class="menu_link" href="{{url_for('users.account') }}">
                <i class="fa fa-user icon-left" style=""></i>
                Profile
            </a>
            <a class="menu_link" href="{{ url_for('users.logout') }}"><i
                    class="fa fa-sign-out"></i>Exit</a>
        {% else %}
            <a class="menu_link" href="{{url_for('users.login') }}">Enter</a>
            <a class="menu_link" href="{{url_for('users.register') }}">Register</a>
        {% endif %}
    </div>

    <main class="tm-main ">
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div class="alert alert-{{ category }}">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}
        {% block content %} {% endblock content %}
    </main>
</div>
<footer class="row tm-row">
    <hr class="col-12">
    <div class="col-md-6 col-12 tm-color-gray">
        Design: <a rel="nofollow" target="_parent"
                   href="https://templatemo.com"
                   class="tm-external-link">TemplateMo</a>
    </div>
    <div class="col-md-6 col-12 tm-color-gray tm-copyright">
        Copyright 2020 Academy-GB Blog Company Co. Ltd.
    </div>
</footer>
<script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/menu-active.js') }}"></script>
<script src="{{ url_for('static', filename='js/templatemo-script.js') }}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script src="https://kit.fontawesome.com/4b9ba14b0f.js" crossorigin="anonymous"></script>
</body>
</html>

flask_project/templates/index.html
{% extends "base.html" %}

{% block content %}
<div>
    <!-- Search form -->
    <div class="row tm-row">
        <div class="col-12">
            <form method="GET" class="form-inline tm-mb-80 tm-search-form">
                <input class="form-control tm-search-input" name="query"
                       type="text" placeholder="Search..."
                       aria-label="Search">
                <button class="tm-search-button" type="submit">
                    <i class="fas fa-search tm-search-icon"
                       aria-hidden="true"></i>
                </button>
            </form>
        </div>
    </div>
    <div class="row tm-row">
        {% for post in posts.items %}
        <article class="col-12 col-md-6 tm-post">
            <hr class="tm-hr-primary">
                <a href="{{ url_for('posts.post', post_id=post.id) }}" class="deactivate-link  effect-lily">
                    <div class="tm-post-link-inner">
                        {% if post.image_file %}
                            <img src="{{ url_for('static', filename='img/posts_image/' + post.image_file) }}"
                                 alt="Image" class="img-fluid">
                        {% else %}
                            <img src="{{ url_for('static', filename='img/posts_image/default.jpg') }}"
                                 alt="Image" class="img-fluid">
                        {% endif %}
                    </div>
                        <!-- Flag - new posts. -->
                        {% if (datetime.datetime.utcnow() - post.date_posted)
                            < datetime.timedelta(hours=24) %}
                            <span class="position-absolute tm-new-badge">New</span>
                        {% endif %}
                    <h2 class="tm-pt-30 tm-color-primary tm-post-title ">
                            {{ post.title }}
                    </h2>
                </a>
            <p class="tm-pt-30">
                {{ post.content }}
            </p>
            <div class="d-flex justify-content-between tm-pt-45">

                    <a href="{{ url_for('posts.user_posts', user_id=post.author.id) }}"
                       class="tm-color-primary">
                        Author post - {{ post.author.username }}.
                    </a>
                <span class="tm-color-primary">
                    {{ post.date_posted.date() }}</span>
            </div>
            <hr>
        </article>
    {% endfor %}
    </div>
    <div class="row tm-row tm-mb-75">
        <div class="tm-paging-wrapper">
            <nav class="tm-paging-nav d-inline-block">
                <ul>
                    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
                        {% if page_num %}
                            {% if posts.page == page_num %}
                                <li class="tm-paging-item active">
                                    <a class="mb-2 tm-btn tm-paging-link" href="{{ url_for('posts.allpost', page=page_num) }}">{{ page_num }}</a>
                                </li>
                            {% else %}
                                <li class="tm-paging-item">
                                    <a class="mb-2 tm-btn tm-paging-link" href="{{ url_for('posts.allpost', page=page_num) }}">{{ page_num }}</a>
                                </li>
                            {% endif %}
                        {% else %}
                            ...
                        {% endif %}
                    {% endfor %}
                </ul>
            </nav>
        </div>
    </div>
</div>
{% endblock content %}

flask_project/templates/login.html
{% extends "base.html" %}

{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Authorization</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
           </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
                <button class="btn btn-outline-info">
                 <a class="btn-outline-info" href="{{ url_for('users.reset_request') }}">Forgot your password?</a>
            </button>
            </div>
            <small class="btn-outline-info">
                Need an account? <a class="btn-outline-info" href="{{ url_for('users.register') }}">Register</a>
            </small>
        </form>
    </div>
{% endblock content %}

flask_project/templates/post.html
{% extends "base.html" %}

{% block content %}
<div class="container flex-column" style="display: flex;">
  <article class="col-12 col-md-6">
      <hr class="tm-hr-primary">
              <div>
                  <img src="{{ url_for('static', filename='img/posts_image/' + post.image_file) }}"
                       alt="Image" class="img-fluid">
              </div>
                  <!-- Flag - new posts. -->
                  {% if (datetime.datetime.utcnow() - post.date_posted)
                      < datetime.timedelta(hours=24) %}
                      <span class="position-absolute tm-new-badge" style="right: 15px;">New</span>
                  {% endif %}
              <h2 class="tm-pt-30 tm-color-primary tm-post-title ">
                      {{ post.title }}
              </h2>
      <p class="tm-pt-30">
          {{ post.content }}
      </p>
      <div class="d-flex justify-content-between tm-pt-45">
          <span class="tm-color-primary">{{ post.author.username }}</span>
          <span class="tm-color-primary">
              {{ post.date_posted.date() }}</span>
      </div>
      <hr>
  </article>
      {% if post.author == current_user %}
        <div class="card-footer" style="border-top: 0;">
          {% if post.author == current_user %}
            <a class="btn btn-update mt-1 mb-1" href="{{url_for('posts.update_post', post_id=post.id) }}">Update</a>
            <button type="button" class="btn btn-delete m-1" data-toggle="modal"  data-target="#deleteModal">Delete</button>
          {% endif %}
        </div>
      {% endif %}

  
<!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Удалить пост?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-update mt-1 mb-1" data-dismiss="modal">Закрыть</button>
          <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
            <input class="btn btn-delete m-1" type="submit" value="Удалить">
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

flask_project/templates/reset_request.html
{% extends "base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset password</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

flask_project/templates/user_posts.html
{% extends "base.html" %}

{% block content %}
<div>
    <!-- Search form -->
    <div class="row tm-row">
        <div class="col-12">
            <form method="GET" class="form-inline tm-mb-80 tm-search-form">
                <input class="form-control tm-search-input" name="query"
                       type="text" placeholder="Search..."
                       aria-label="Search">
                <button class="tm-search-button" type="submit">
                    <i class="fas fa-search tm-search-icon"
                       aria-hidden="true"></i>
                </button>
            </form>
        </div>
    </div>
    <div class="row tm-row">
        <h1 class="mb-3">Посты опубликованы пользователем - {{ current_user.username }} ({{ posts.total }})</h1>
        {% for post in posts.items %}
        <article class="col-12 col-md-6 tm-post">
            <hr class="tm-hr-primary">
                <a href="{{ url_for('posts.post', post_id=post.id) }}" class="deactivate-link  effect-lily">
                    <div class="tm-post-link-inner">
                        {% if post.image_file %}
                            <img src="{{ url_for('static', filename='img/posts_image/' + post.image_file) }}"
                                 alt="Image" class="img-fluid">
                        {% else %}
                            <img src="{{ url_for('static', filename='img/posts_image/default.jpg') }}"
                                 alt="Image" class="img-fluid">
                        {% endif %}
                    </div>
                        <!-- Flag - new posts. -->
                        {% if (datetime.datetime.utcnow() - post.date_posted)
                            < datetime.timedelta(hours=24) %}
                            <span class="position-absolute tm-new-badge">New</span>
                        {% endif %}
                    <h2 class="tm-pt-30 tm-color-primary tm-post-title ">
                            {{ post.title }}
                    </h2>
                </a>
            <p class="tm-pt-30">
                {{ post.content }}
            </p>
            <div class="d-flex justify-content-between tm-pt-45">
                <span class="tm-color-primary">{{ post.author.username }}</span>
                <span class="tm-color-primary">
                    {{ post.date_posted.date() }}</span>
            </div>
            <hr>
        </article>
    {% endfor %}
    </div>
    <div class="row tm-row tm-mb-75">
        <div class="tm-paging-wrapper">
            <nav class="tm-paging-nav d-inline-block">
                <ul>
                    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
                        {% if page_num %}
                            {% if posts.page == page_num %}
                                <li class="tm-paging-item active">
                                    <a class="mb-2 tm-btn tm-paging-link" href="{{ url_for('posts.user_posts',user_id=current_user.id, page=page_num) }}">{{ page_num }}</a>
                                </li>
                            {% else %}
                                <li class="tm-paging-item">
                                    <a class="mb-2 tm-btn tm-paging-link" href="{{ url_for('posts.user_posts', user_id=current_user.id, page=page_num) }}">{{ page_num }}</a>
                                </li>
                            {% endif %}
                        {% else %}
                            ...
                        {% endif %}
                    {% endfor %}
                </ul>
            </nav>
        </div>
    </div>
</div>
{% endblock content %}